/* ArtVenn field atlas. Geometry is data-driven; no third-party requests at runtime. */
(function () {
'use strict';
if (!window.L || !window.ATLAS_DATA) { document.getElementById('map').textContent='The map files could not be loaded. Please check that the complete map folder is present.'; return; }
const D=window.ATLAS_DATA, reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const config={
 overview:{title:'Four fieldwork areas',kicker:'Selected overview',desc:'From China’s inscription landscapes to Mongolia and the Korean and Japanese collections. Choose an area to explore.',bounds:[[17,76],[51.5,143.5]]},
 china:{title:'China',kicker:'Reconstructed corridors',desc:'The supplied footprint screenshot reports 210 cities in China. These 15 sketch segments summarize its visible lines; they are not 15 trips or a complete city list.',bounds:[[17.6,77.5],[50.5,132.5]]},
 mongolia:{title:'Mongolia',kicker:'Two supplied endpoints',desc:'A southbound journey from Ulaanbaatar to the Yanran Inscription. The link indicates the two endpoints, not the road taken.',bounds:[[44.3,102.8],[48.8,108.9]]},
 korea:{title:'South Korea',kicker:'Inscription study areas',desc:'17 supplied inscription entries in 13 city/county areas, spanning Goguryeo, Baekje, Silla, Unified Silla and Goryeo. Visit-by-visit status and itinerary order are not yet established.',bounds:[[34.45,125.95],[37.95,130.1]]},
 japan:{title:'Japan',kicker:'Five named cities',desc:'Tokyo, Nagoya, Kyoto, Osaka and Nara were named as collection-trip destinations. Dashed links are schematic, not a chronology or transport record.',bounds:[[33.7,134.5],[36.25,140.4]]}
};
const latlng=c=>[c[1],c[0]], getColor=g=>getComputedStyle(document.documentElement).getPropertyValue('--'+g).trim();
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
let current='overview',selectedId=null, routeLayers=[], tooltipLayers=[];
const map=L.map('map',{zoomControl:false,attributionControl:true,minZoom:2.2,maxZoom:8.5,zoomSnap:.1,zoomDelta:.5,scrollWheelZoom:false,preferCanvas:false,maxBounds:[[8,62],[61,152]],maxBoundsViscosity:.65,zoomAnimation:!reduced,fadeAnimation:!reduced});
L.control.zoom({position:'topright'}).addTo(map);L.control.scale({position:'bottomleft',imperial:false,maxWidth:90}).addTo(map);
map.attributionControl.setPrefix('<a href="https://leafletjs.com/" target="_blank" rel="noopener">Leaflet</a>');map.attributionControl.addAttribution('Natural Earth · <a href="https://www.geonames.org/" target="_blank" rel="noopener">GeoNames</a>');
map.createPane('geographicLabels');map.getPane('geographicLabels').style.zIndex=420;map.getPane('geographicLabels').style.pointerEvents='none';
const base=L.layerGroup().addTo(map),routes=L.layerGroup().addTo(map),points=L.layerGroup().addTo(map),labels=L.layerGroup().addTo(map);
function drawBase(){base.clearLayers();const styles=getComputedStyle(document.documentElement);L.geoJSON(D.land,{interactive:false,style:{fillColor:styles.getPropertyValue('--land').trim(),fillOpacity:1,color:styles.getPropertyValue('--land-line').trim(),weight:.7,smoothFactor:.35}}).addTo(base);L.geoJSON(D.borders,{interactive:false,style:{color:styles.getPropertyValue('--land-line').trim(),weight:.65,opacity:.7,dashArray:'3 3'}}).addTo(base);}
function addGeoLabel(text,coord,water){const n=el('div','geo-label'+(water?' water':''),text);L.marker(latlng(coord),{interactive:false,keyboard:false,pane:'geographicLabels',icon:L.divIcon({html:n,className:'',iconSize:[140,20],iconAnchor:[70,10]})}).addTo(labels);}
function updateLabels(){labels.clearLayers();if(!document.getElementById('labels').checked)return;
 if(current==='overview'||current==='china'){
 [['CHINA',[106,37.8]],['MONGOLIA',[100.6,46.5]],['SOUTH KOREA',[129.8,33.3]],['JAPAN',[139.3,39]],['RUSSIA',[121,53]],['INDIA',[79,27]],['VIETNAM',[107,16]]].forEach(x=>addGeoLabel(x[0],x[1],false));
 addGeoLabel('Pacific Ocean',[140,24],true);
 (D.labels||[]).filter(x=>['Lhasa','Zhengzhou','Beijing','Shanghai','Urumqi','Chengdu','Kunming','Harbin'].includes(x.name)).forEach(x=>{const m=L.circleMarker(latlng(x.coord),{radius:1.8,weight:0,fillColor:getComputedStyle(document.documentElement).getPropertyValue('--muted').trim(),fillOpacity:.85,interactive:false}).bindTooltip(x.name,{permanent:true,direction:'right',offset:[4,0],className:'place-label context-label'}).addTo(labels);});
 }else if(current==='japan'){addGeoLabel('JAPAN',[138,36.15],false);addGeoLabel('Pacific Ocean',[138.7,34.1],true);}else if(current==='mongolia'){addGeoLabel('MONGOLIA',[103.5,48.2],false);}else{addGeoLabel('SOUTH KOREA',[127,35],false);}
 if(document.getElementById('labels').checked)tooltipLayers.forEach(m=>m.openTooltip());
}
function pointPopup(f){const p=f.properties,n=el('div');n.append(el('h3','',p.name),el('small','',p.kind==='survey_area'?'City/county area · individual visit unconfirmed':p.kind==='reported_site'?'Reported field site · approximate public location':'Reported city · city-level locator'));const txt=p.items.length?p.items.length+' inscription '+(p.items.length===1?'entry':'entries')+' associated with this area.':p.description;n.append(el('p','',txt));const b=el('button','', 'View details →');b.type='button';b.addEventListener('click',()=>{showPoint(f);map.closePopup();});n.append(b);return n;}
function addPoint(f){const p=f.properties,marker=L.circleMarker(latlng(f.geometry.coordinates),{radius:current==='overview'?4:6,color:getColor(p.group),weight:1.7,fillColor:p.kind==='survey_area'?getComputedStyle(document.documentElement).getPropertyValue('--paper').trim():getColor(p.group),fillOpacity:1});marker.bindPopup(pointPopup(f),{maxWidth:280,autoPan:true});if(current!=='overview'&&document.getElementById('labels').checked){marker.bindTooltip(p.name,{permanent:true,direction:['Osaka','Seoul','Boryeong','Yeoju','Daegu'].includes(p.name)?'left':['Wonju','Pohang'].includes(p.name)?'top':'right',offset:['Osaka','Seoul','Boryeong','Yeoju','Daegu'].includes(p.name)?[-8,0]:['Wonju','Pohang'].includes(p.name)?[0,-8]:[8,0],className:'place-label'});tooltipLayers.push(marker);}marker.on('click',()=>showPoint(f));marker.addTo(points);return marker;}
function addAggregate(group,name,coord){const c=getColor(group),m=L.circleMarker(latlng(coord),{radius:9,color:c,weight:2,fillColor:c,fillOpacity:.16}).bindTooltip(name,{permanent:true,direction:'right',offset:[12,0],className:'place-label'});m.on('click',()=>selectRegion(group));m.addTo(points);}
function schematicFeatures(){const byId=Object.fromEntries(D.places.features.map(f=>[f.properties.id,f]));const get=id=>byId[id].geometry.coordinates;const make=(id,g,ids)=>({type:'Feature',properties:{id,group:g,kind:'schematic_link',name:g==='japan'?'Japan — schematic city connections':'Mongolia — supplied endpoint connection',description:'Schematic connection between supplied places. Does not represent a GPS track, travel order, road or transport mode.'},geometry:{type:'LineString',coordinates:ids.map(get)}});return [make('mn-link','mongolia',['mn-ulaanbaatar','mn-yanran']),make('jp-main','japan',['jp-tokyo','jp-nagoya','jp-kyoto','jp-osaka','jp-nara'])];}
const schematic=schematicFeatures();
function drawRoutes(){routes.clearLayers();routeLayers=[];if(!document.getElementById('routes').checked)return;
 const wanted=D.traces.features.concat(schematic).filter(f=>current==='overview'||f.properties.group===current);
 wanted.forEach(f=>{const p=f.properties;const styles={color:getColor(p.group),weight:p.kind==='sketch_trace'?1.9:2.1,opacity:current==='overview'?.85:.94,dashArray:p.kind==='sketch_trace'?'5 4':'7 6',lineCap:'round',lineJoin:'round',smoothFactor:0};if(p.source_dashed)styles.dashArray='3 7';const layer=L.geoJSON(f,{style:styles,onEachFeature:(_,l)=>l.bindTooltip(p.name,{sticky:true})}).addTo(routes);layer.on('click',()=>{if(p.kind==='sketch_trace'){showTrace(f);highlightTrace(p.id);}else showRegion(current==='overview'?p.group:current);});routeLayers.push({id:p.id,layer});});}
function highlightTrace(id){routeLayers.forEach(x=>x.layer.setStyle({opacity:x.id===id?1:.3,weight:x.id===id?3:1.6}));}
function drawPoints(){points.clearLayers();tooltipLayers=[];const fs=D.places.features;if(current==='overview'){fs.forEach(addPoint);}else fs.filter(f=>f.properties.group===current).forEach(addPoint);}
const panel=document.getElementById('inspector');
function initPanel(kicker,title,desc){panel.dataset.view=current;panel.replaceChildren(el('p','panel-kicker',kicker),el('h2','',title));if(desc)panel.append(el('p','panel-desc',desc));panel.scrollTop=0;}
function showRegion(g){const c=config[g];selectedId=null;initPanel(c.kicker,c.title,c.desc);
 if(g==='overview'){const list=el('div','region-list');[['china','210 cities reported in China'],['mongolia','Ulaanbaatar → Yanran Inscription'],['korea','13 areas · 17 inscription entries'],['japan','Tokyo, Nagoya & Kansai']].forEach(([key,sub])=>{const b=el('button','region-card');b.type='button';const text=el('span');text.append(el('strong','',config[key].title),el('small','',sub));b.append(el('i','dot '+key),text,el('span','arrow','↗'));b.addEventListener('click',()=>selectRegion(key));list.append(b);});panel.append(list,el('p','panel-note','No worldwide city total is inferred. The map combines a travel sketch with selected places supplied separately.'));
 }else if(g==='china'){panel.append(el('p','pill','15 editable sketch segments · no route order'));const list=el('ul','trace-list');D.traces.features.forEach(f=>{const li=el('li'),b=el('button','',f.properties.id+' · '+f.properties.name);b.type='button';b.addEventListener('click',()=>{showTrace(f);highlightTrace(f.properties.id);const bnd=L.geoJSON(f).getBounds();map.fitBounds(bnd,{padding:[45,60],maxZoom:5.5,animate:false});});li.append(b);list.append(li);});panel.append(list);
 }else{const list=el('ul','place-list');D.places.features.filter(f=>f.properties.group===g).forEach(f=>{const p=f.properties,li=el('li'),b=el('button');b.type='button';b.append(el('span','',p.name),el('small','',p.items.length?p.items.length+' '+(p.items.length===1?'entry':'entries'):'↗'));b.addEventListener('click',()=>{showPoint(f);map.setView(latlng(f.geometry.coordinates),g==='japan'?7.8:g==='korea'?7:6.5,{animate:false});});li.append(b);list.append(li);});panel.append(list);if(g==='korea')panel.append(el('p','panel-note','The marker is a regional locator. Original monument sites and present museum locations must be distinguished before publishing exact site coordinates.'));}
 notifyHeight();}
function showPoint(f){const p=f.properties;selectedId=p.id;if(current==='overview')selectRegion(p.group);initPanel(config[p.group].title,p.name,p.description);const b=el('button','back','← All '+config[p.group].title+' locations');b.type='button';b.addEventListener('click',()=>showRegion(p.group));panel.prepend(b);panel.append(el('p','pill',p.kind==='survey_area'?'Regional locator · visit status unconfirmed':p.kind==='reported_site'?'Approximate public site position':'City-level locator'));
 if(p.items.length){const ul=el('ul','detail-items');p.items.forEach(t=>ul.append(el('li','',t)));panel.append(ul);}const src=el('p','panel-note','Coordinate source: '+(p.source.startsWith('https:')?'GeoNames (CC BY 4.0)':p.source));panel.append(src);notifyHeight();}
function showTrace(f){initPanel('Hand-drawn source / '+f.properties.id,f.properties.name,f.properties.description);const b=el('button','back','← All China sketch segments');b.type='button';b.addEventListener('click',()=>selectRegion('china'));panel.prepend(b);panel.append(el('p','pill','Original sketch group: '+f.properties.source_color),el('p','panel-note','Approximate geographic registration. Do not use this line to infer an exact road, a stop, an international crossing, distance or travel direction.'));notifyHeight();}
function fitRegion(g){map.fitBounds(config[g].bounds,{padding:[28,42],animate:false,duration:.4});}
function selectRegion(g){if(!config[g])return;current=g;map.closePopup();document.querySelectorAll('[data-region]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.region===g)));drawRoutes();drawPoints();updateLabels();showRegion(g);fitRegion(g);}
function cleanLabels(){document.querySelectorAll('.place-label').forEach(n=>{n.style.visibility='visible';});}
map.on('moveend zoomend',()=>setTimeout(cleanLabels,30));
document.querySelectorAll('[data-region]').forEach(b=>b.addEventListener('click',()=>selectRegion(b.dataset.region)));
document.getElementById('reset').addEventListener('click',()=>selectRegion(current));document.getElementById('routes').addEventListener('change',drawRoutes);document.getElementById('labels').addEventListener('change',()=>{drawPoints();updateLabels();cleanLabels();});
document.getElementById('expand').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.atlas').requestFullscreen();}catch(_){window.open(window.location.href,'_blank','noopener');}});
document.addEventListener('fullscreenchange',()=>{document.getElementById('expand').textContent=document.fullscreenElement?'Exit full screen':'Expand ↗';setTimeout(()=>{map.invalidateSize();fitRegion(current);notifyHeight();},50);});
document.getElementById('download').addEventListener('click',()=>{const geo={type:'FeatureCollection',name:'ArtVenn selected routes and places',features:D.traces.features.concat(D.places.features,schematic)};const url=URL.createObjectURL(new Blob([JSON.stringify(geo,null,2)],{type:'application/geo+json'})),a=el('a');a.href=url;a.download='artvenn-field-atlas.geojson';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);});
let heightTimer;function notifyHeight(){clearTimeout(heightTimer);heightTimer=setTimeout(()=>{if(window.parent!==window)window.parent.postMessage({type:'artvenn:field-atlas:height',height:Math.ceil(document.querySelector('.atlas').getBoundingClientRect().height)},window.location.origin==='null'?'*':window.location.origin);},80);}
new ResizeObserver(()=>{map.invalidateSize({pan:false});notifyHeight();}).observe(document.querySelector('.atlas'));document.querySelector('.method').addEventListener('toggle',notifyHeight);
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{drawBase();drawRoutes();drawPoints();updateLabels();});
drawBase();selectRegion('overview');notifyHeight();window.__atlas={map,selectRegion,data:D,ready:true};
}());
